"""
Copyright (C) 2025 Mahesh Vaijainthymala Krishnamoorthy (Mahesh Vaikri)

This file is part of MAPLE - Multi Agent Protocol Language Engine.

MAPLE - Multi Agent Protocol Language Engine is free software: you can redistribute it and/or
modify it under the terms of the GNU Affero General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later version.
MAPLE - Multi Agent Protocol Language Engine is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU Affero General Public License for more details. You should have
received a copy of the GNU Affero General Public License along with MAPLE - Multi Agent Protocol
Language Engine. If not, see <https://www.gnu.org/licenses/>.
"""

# MAPLE Autonomy Layer - Autonomous agentic AI capabilities.

from .agent import AutonomousAgent, AutonomousConfig, Goal, ReasoningStep
from .approval import (
    ApprovalDecision,
    ApprovalRequest,
    ApprovalStore,
    FileApprovalStore,
    InMemoryApprovalStore,
)
from .artifacts import (
    Artifact,
    ArtifactStore,
    CodeBlock,
    FileArtifactStore,
    InMemoryArtifactStore,
    extract_code_blocks,
)
from .contracts import (
    Guardrail,
    parse_structured_output,
    parse_typed_output,
    run_guardrails,
    schema_guardrail,
    structured_model_schema,
    validate_json_schema,
    validate_typed_value,
)
from .evaluation import (
    EvalCase,
    EvalObservation,
    EvalReport,
    EvalResult,
    EvaluationHarness,
    GroundednessEvalCase,
    GroundednessObservation,
    GroundingSource,
    RetrievalEvalCase,
)
from .events import (
    AgentEvent,
    EventBatch,
    EventCursor,
    EventExporter,
    EventStream,
    RedactionPolicy,
)
from .interactions import (
    FileHumanInputStore,
    HumanInputAuthorizer,
    HumanInputDecision,
    HumanInputNotification,
    HumanInputNotifier,
    HumanInputRound,
    HumanInputRequest,
    HumanInputStore,
    InMemoryHumanInputStore,
)
from .execution import (
    CancellationToken,
    ExecutionExecutor,
    ExecutionPolicy,
    TrustedLocalExecutor,
)
from .interop import InteropEnvelope, round_trip_json
from .mcp_tools import discover_mcp_tools, register_mcp_tools
from .memory import EpisodicMemory, MemoryManager, SemanticMemory, WorkingMemory
from .observability import AgentSnapshot, DecisionLogger, DecisionTrace
from .orchestrator import AgentOrchestrator, TeamMember
from .replay import (
    DEFAULT_MAX_RECORD_BYTES,
    DEFAULT_MAX_RECORDS,
    DEFAULT_MAX_RUN_RECORDS,
    ExecutionJournal,
    ExecutionRecord,
    FileExecutionJournal,
    InMemoryExecutionJournal,
)
from .retrieval import (
    ChunkingPolicy,
    Document,
    DocumentChunk,
    EmbeddingProvider,
    InMemoryLexicalRetriever,
    InMemoryVectorRetriever,
    RetrievalBackend,
    RetrievalHit,
    SourceRef,
    TextChunker,
    VectorRetrievalHit,
)
from .runs import (
    DEFAULT_MAX_RUN_BYTES,
    DEFAULT_MAX_RUN_MESSAGES,
    DEFAULT_MAX_RUN_TRACE,
    AgentRunCheckpoint,
    AgentRunStore,
    FileAgentRunStore,
    InMemoryAgentRunStore,
)
from .server import RunServer, WorkflowRegistry
from .sessions import (
    DEFAULT_MAX_MESSAGE_BYTES,
    DEFAULT_MAX_MESSAGES,
    DEFAULT_MAX_METADATA_BYTES,
    DEFAULT_MAX_SESSION_BYTES,
    DEFAULT_MAX_SESSIONS,
    FileSessionStore,
    InMemorySessionStore,
    SessionMessage,
    SessionSnapshot,
    SessionStore,
)
from .tools import Tool, ToolRegistry, create_handoff_tool
from .workflow import (
    END,
    CheckpointStore,
    FileCheckpointStore,
    HistoryCheckpointStore,
    InMemoryCheckpointStore,
    Workflow,
    WorkflowCheckpoint,
    WorkflowContext,
    WorkflowPause,
    WorkflowRun,
    RetryPolicy,
)

__all__ = [
    "Tool",
    "ToolRegistry",
    "create_handoff_tool",
    "WorkingMemory",
    "EpisodicMemory",
    "SemanticMemory",
    "MemoryManager",
    "AutonomousAgent",
    "AutonomousConfig",
    "Goal",
    "ReasoningStep",
    "AgentOrchestrator",
    "TeamMember",
    "DecisionTrace",
    "DecisionLogger",
    "AgentSnapshot",
    "discover_mcp_tools",
    "register_mcp_tools",
    "Guardrail",
    "parse_structured_output",
    "parse_typed_output",
    "run_guardrails",
    "schema_guardrail",
    "structured_model_schema",
    "validate_json_schema",
    "validate_typed_value",
    "CancellationToken",
    "ExecutionExecutor",
    "ExecutionPolicy",
    "TrustedLocalExecutor",
    "ChunkingPolicy",
    "Document",
    "DocumentChunk",
    "EmbeddingProvider",
    "InMemoryLexicalRetriever",
    "InMemoryVectorRetriever",
    "RetrievalBackend",
    "RetrievalHit",
    "SourceRef",
    "TextChunker",
    "VectorRetrievalHit",
    "DEFAULT_MAX_RUN_BYTES",
    "DEFAULT_MAX_RUN_MESSAGES",
    "DEFAULT_MAX_RUN_TRACE",
    "AgentRunCheckpoint",
    "AgentRunStore",
    "FileAgentRunStore",
    "InMemoryAgentRunStore",
    "AgentEvent",
    "EventBatch",
    "EventCursor",
    "EventExporter",
    "EventStream",
    "RedactionPolicy",
    "HumanInputDecision",
    "HumanInputNotification",
    "HumanInputNotifier",
    "HumanInputAuthorizer",
    "HumanInputRound",
    "HumanInputRequest",
    "HumanInputStore",
    "FileHumanInputStore",
    "InMemoryHumanInputStore",
    "EvalCase",
    "EvalObservation",
    "EvalReport",
    "EvalResult",
    "EvaluationHarness",
    "GroundednessEvalCase",
    "GroundednessObservation",
    "GroundingSource",
    "RetrievalEvalCase",
    "InteropEnvelope",
    "round_trip_json",
    "Artifact",
    "ArtifactStore",
    "CodeBlock",
    "FileArtifactStore",
    "InMemoryArtifactStore",
    "extract_code_blocks",
    "ApprovalDecision",
    "ApprovalRequest",
    "ApprovalStore",
    "FileApprovalStore",
    "InMemoryApprovalStore",
    "END",
    "CheckpointStore",
    "FileCheckpointStore",
    "HistoryCheckpointStore",
    "InMemoryCheckpointStore",
    "Workflow",
    "WorkflowCheckpoint",
    "WorkflowContext",
    "WorkflowPause",
    "WorkflowRun",
    "RetryPolicy",
    "DEFAULT_MAX_MESSAGES",
    "DEFAULT_MAX_MESSAGE_BYTES",
    "DEFAULT_MAX_METADATA_BYTES",
    "DEFAULT_MAX_SESSION_BYTES",
    "DEFAULT_MAX_SESSIONS",
    "FileSessionStore",
    "InMemorySessionStore",
    "SessionMessage",
    "SessionSnapshot",
    "SessionStore",
    "RunServer",
    "WorkflowRegistry",
    "DEFAULT_MAX_RECORD_BYTES",
    "DEFAULT_MAX_RECORDS",
    "DEFAULT_MAX_RUN_RECORDS",
    "ExecutionJournal",
    "ExecutionRecord",
    "FileExecutionJournal",
    "InMemoryExecutionJournal",
]
