name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Code formatting check
      run: |
        black --check --diff maple/
        isort --check-only --diff maple/
    
    - name: Documentation check
      run: |
        pip install pydoc-markdown
        pydoc-markdown --check
    
    - name: License check
      run: |
        # Ensure all Python files have correct license header
        python scripts/check_license_headers.py
    
    - name: Performance regression check
      run: |
        python tests/comprehensive_test_suite.py
        # Ensure we maintain 32/32 test success and 33x performance
